include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_overrides: true
    always_declare_return_types: true
    avoid_escaping_inner_quotes: true
    avoid_setters_without_getters: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    no_default_cases: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    test_types_in_equals: true
    unawaited_futures: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unsafe_html: true
    use_raw_strings: true
    sized_box_for_whitespace: true
    prefer_const_constructors: true
    comment_references: true
    avoid_multiple_declarations_per_line: true
    noop_primitive_operations: true
    cascade_invocations: true
    avoid_redundant_argument_values: true
    lines_longer_than_80_chars: true
    prefer_int_literals: true
    prefer_const_constructors_in_immutables: true
    avoid_void_async: true
    require_trailing_commas: true
